databases:
  - name: ToDo App db
    databaseName: to_do_app_production
    user: to_do_app_production_user
    region: singapore

services:
  - type: web
    name: ToDoApp
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
